apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cmp-cm
data:
  argocd-lint.yaml: |
    apiVersion: argoproj.io/v1alpha1
    kind: ConfigManagementPlugin
    metadata:
      name: argocd-lint
    spec:
      version: v1
      discover:
        command: ["/bin/sh", "-c"]
        args:
          - |
            find "$ARGOCD_APP_BASE_DIR" -maxdepth 2 -name '.argocd-lint' -print -quit | grep -q . || \
            find "$ARGOCD_APP_BASE_DIR" -maxdepth 2 -type f \( -name '*.yaml' -o -name '*.yml' \) -print -quit | grep -q .
      generate:
        command: ["/bin/sh", "-c"]
        args:
          - |
            set -euo pipefail

            THRESHOLD=${ARGOCD_LINT_THRESHOLD:-error}
            PLUGIN_ARGS=${ARGOCD_LINT_ARGS:-}

            argocd-lint "$ARGOCD_APP_BASE_DIR" \
              --severity-threshold="$THRESHOLD" \
              --plugin-dir /opt/argocd-lint/bundles/core \
              $PLUGIN_ARGS

            find "$ARGOCD_APP_BASE_DIR" -type f \( -name '*.yaml' -o -name '*.yml' \) \
              -print0 | xargs -0 -I{} sh -c 'echo "---"; cat "{}"'
