name: CI

on:
  push:
    branches: [ main ]
  pull_request: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Verify gofmt
        run: |
          gofmt -w $(find . -name '*.go' -not -path './vendor/*')
          git diff --exit-code

      - name: Tidy
        run: go mod tidy

      - name: Ensure module files clean
        run: git diff --exit-code go.mod go.sum

      - name: Build
        run: go build ./...

      - name: Test
        run: go test ./...

      - name: Lint sample manifests
        run: |
          go build -o ./bin/argocd-lint ./cmd/argocd-lint
          ./bin/argocd-lint examples/apps --format table
