name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, darwin, windows]
        goarch: [amd64, arm64]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Build
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
        run: |
          mkdir -p dist
          EXT=""
          if [ "$GOOS" = "windows" ]; then
            EXT=".exe"
          fi
          OUTPUT="dist/argocd-lint-${GOOS}-${GOARCH}${EXT}"
          VERSION="${GITHUB_REF_NAME#v}"
          if [ -z "$VERSION" ]; then
            VERSION="dev"
          fi
          LDFLAGS="-X github.com/argocd-lint/argocd-lint/pkg/version.Version=${VERSION} -X github.com/argocd-lint/argocd-lint/pkg/version.GitCommit=${GITHUB_SHA} -X github.com/argocd-lint/argocd-lint/pkg/version.BuildDate=$(date -u +%Y-%m-%dT%H:%M:%SZ)"
          go build -ldflags "$LDFLAGS" -o "$OUTPUT" ./cmd/argocd-lint

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: argocd-lint-${{ matrix.goos }}-${{ matrix.goarch }}
          path: dist/argocd-lint-${{ matrix.goos }}-${{ matrix.goarch }}*

  publish:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist

      - name: Generate checksums
        run: |
          cd dist
          find . -type f -exec sha256sum {} \; > checksums.txt

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/**/*
          body: |
            Automated release of argocd-lint
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
